# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master

  paths:
    exclude:
    - README.md

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscriptionEndpoint: unb-azure-resource
  azureContainerRegistry: rfidregistry.azurecr.io

steps:
- task: DockerCompose@0
  inputs:
    azureSubscriptionEndpoint: 'unb-azure-resource'
    azureContainerRegistry: '{"loginServer":"rfidregistry.azurecr.io", "id" : "/subscriptions/aeaacfab-b4c6-4bce-b4a5-6d3d18551a72/resourceGroups/unb-prod-rg/providers/Microsoft.ContainerRegistry/registries/rfidregistry"}'
    action: 'Run a Docker Compose command'