FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY ["services/asset/Asset.API/Asset.API.csproj", "services/asset/Asset.API/"]
RUN dotnet restore "services/asset/Asset.API/Asset.API.csproj"
COPY . .
WORKDIR "/src/services/asset/Asset.API"
RUN dotnet build "Asset.API.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Asset.API.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Asset.API.dll"]