version: '3.4'

services:
  ocelot.api:
    image: ${DOCKER_REGISTRY-}ocelotapi
    build:
      context: .
      dockerfile: gateway/ocelot/Ocelot.API/Dockerfile

  sso.api:
    image: ${DOCKER_REGISTRY-}ssoapi
    build:
      context: .
      dockerfile: security/sso/SSO.API/Dockerfile


  read.api:
    image: ${DOCKER_REGISTRY-}readapi
    build:
      context: .
      dockerfile: services/read/Read.API/Dockerfile


  telemetry.api:
    image: ${DOCKER_REGISTRY-}telemetryapi
    build:
      context: .
      dockerfile: services/telemetry/Telemetry.API/Dockerfile


  asset.api:
    image: ${DOCKER_REGISTRY-}assetapi
    build:
      context: .
      dockerfile: services/asset/Asset.API/Dockerfile

